// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: api/proto/v1/notifications.proto

package v1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventID_Enum int32

const (
	EventID_LIKE_POST    EventID_Enum = 0
	EventID_LIKE_COMMENT EventID_Enum = 1
	EventID_COMMENT      EventID_Enum = 2
	EventID_FOLLOW       EventID_Enum = 3
)

// Enum value maps for EventID_Enum.
var (
	EventID_Enum_name = map[int32]string{
		0: "LIKE_POST",
		1: "LIKE_COMMENT",
		2: "COMMENT",
		3: "FOLLOW",
	}
	EventID_Enum_value = map[string]int32{
		"LIKE_POST":    0,
		"LIKE_COMMENT": 1,
		"COMMENT":      2,
		"FOLLOW":       3,
	}
)

func (x EventID_Enum) Enum() *EventID_Enum {
	p := new(EventID_Enum)
	*p = x
	return p
}

func (x EventID_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventID_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_notifications_proto_enumTypes[0].Descriptor()
}

func (EventID_Enum) Type() protoreflect.EnumType {
	return &file_api_proto_v1_notifications_proto_enumTypes[0]
}

func (x EventID_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventID_Enum.Descriptor instead.
func (EventID_Enum) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_notifications_proto_rawDescGZIP(), []int{2, 0}
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	TriggerId         string               `protobuf:"bytes,3,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	Event             *Event               `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	UserWhoFiredEvent *UserWhoFiredEvent   `protobuf:"bytes,5,opt,name=user_who_fired_event,json=userWhoFiredEvent,proto3" json:"user_who_fired_event,omitempty"`
	Read              bool                 `protobuf:"varint,6,opt,name=read,proto3" json:"read,omitempty"`
	Content           string               `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_notifications_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notifications_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetDate() *timestamp.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Notification) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *Notification) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Notification) GetUserWhoFiredEvent() *UserWhoFiredEvent {
	if x != nil {
		return x.UserWhoFiredEvent
	}
	return nil
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   EventID_Enum `protobuf:"varint,1,opt,name=id,proto3,enum=v1.EventID_Enum" json:"id,omitempty"`
	Text string       `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_notifications_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notifications_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() EventID_Enum {
	if x != nil {
		return x.Id
	}
	return EventID_LIKE_POST
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EventID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventID) Reset() {
	*x = EventID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_notifications_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventID) ProtoMessage() {}

func (x *EventID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notifications_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventID.ProtoReflect.Descriptor instead.
func (*EventID) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notifications_proto_rawDescGZIP(), []int{2}
}

type UserWhoFiredEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *UserWhoFiredEvent) Reset() {
	*x = UserWhoFiredEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_notifications_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserWhoFiredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWhoFiredEvent) ProtoMessage() {}

func (x *UserWhoFiredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notifications_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWhoFiredEvent.ProtoReflect.Descriptor instead.
func (*UserWhoFiredEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *UserWhoFiredEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserWhoFiredEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetAllNotificationsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notifications []*Notification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *GetAllNotificationsRes) Reset() {
	*x = GetAllNotificationsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_notifications_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllNotificationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNotificationsRes) ProtoMessage() {}

func (x *GetAllNotificationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notifications_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNotificationsRes.ProtoReflect.Descriptor instead.
func (*GetAllNotificationsRes) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllNotificationsRes) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type ReadNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
}

func (x *ReadNotificationRequest) Reset() {
	*x = ReadNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_notifications_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotificationRequest) ProtoMessage() {}

func (x *ReadNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notifications_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotificationRequest.ProtoReflect.Descriptor instead.
func (*ReadNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *ReadNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type ReadNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notification *Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
}

func (x *ReadNotificationResponse) Reset() {
	*x = ReadNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_notifications_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotificationResponse) ProtoMessage() {}

func (x *ReadNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notifications_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotificationResponse.ProtoReflect.Descriptor instead.
func (*ReadNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *ReadNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_api_proto_v1_notifications_proto protoreflect.FileDescriptor

var file_api_proto_v1_notifications_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x02, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x14, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x77, 0x68, 0x6f, 0x5f, 0x66, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x57, 0x68, 0x6f, 0x46, 0x69, 0x72, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x11, 0x75,
	0x73, 0x65, 0x72, 0x57, 0x68, 0x6f, 0x46, 0x69, 0x72, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x72, 0x65, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3d,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x4b, 0x0a,
	0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x40, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d,
	0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x49, 0x4b, 0x45, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x4c, 0x49, 0x4b, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x03, 0x22, 0x3f, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x57, 0x68, 0x6f, 0x46, 0x69, 0x72, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76,
	0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x42, 0x0a,
	0x17, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x50, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a,
	0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_notifications_proto_rawDescOnce sync.Once
	file_api_proto_v1_notifications_proto_rawDescData = file_api_proto_v1_notifications_proto_rawDesc
)

func file_api_proto_v1_notifications_proto_rawDescGZIP() []byte {
	file_api_proto_v1_notifications_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_notifications_proto_rawDescData)
	})
	return file_api_proto_v1_notifications_proto_rawDescData
}

var file_api_proto_v1_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_v1_notifications_proto_goTypes = []interface{}{
	(EventID_Enum)(0),                // 0: v1.EventID.Enum
	(*Notification)(nil),             // 1: v1.Notification
	(*Event)(nil),                    // 2: v1.Event
	(*EventID)(nil),                  // 3: v1.EventID
	(*UserWhoFiredEvent)(nil),        // 4: v1.UserWhoFiredEvent
	(*GetAllNotificationsRes)(nil),   // 5: v1.GetAllNotificationsRes
	(*ReadNotificationRequest)(nil),  // 6: v1.ReadNotificationRequest
	(*ReadNotificationResponse)(nil), // 7: v1.ReadNotificationResponse
	(*timestamp.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_api_proto_v1_notifications_proto_depIdxs = []int32{
	8, // 0: v1.Notification.date:type_name -> google.protobuf.Timestamp
	2, // 1: v1.Notification.event:type_name -> v1.Event
	4, // 2: v1.Notification.user_who_fired_event:type_name -> v1.UserWhoFiredEvent
	0, // 3: v1.Event.id:type_name -> v1.EventID.Enum
	1, // 4: v1.GetAllNotificationsRes.notifications:type_name -> v1.Notification
	1, // 5: v1.ReadNotificationResponse.notification:type_name -> v1.Notification
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_v1_notifications_proto_init() }
func file_api_proto_v1_notifications_proto_init() {
	if File_api_proto_v1_notifications_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_notifications_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_notifications_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_notifications_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_notifications_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserWhoFiredEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_notifications_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllNotificationsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_notifications_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_notifications_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_notifications_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_notifications_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_notifications_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_notifications_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_notifications_proto_msgTypes,
	}.Build()
	File_api_proto_v1_notifications_proto = out.File
	file_api_proto_v1_notifications_proto_rawDesc = nil
	file_api_proto_v1_notifications_proto_goTypes = nil
	file_api_proto_v1_notifications_proto_depIdxs = nil
}
