apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: unpaper
spec:
  immediateDeploy: true
  connection:
    postgres:
      uri:
        valueFrom:
          secretKeyRef:
            name: secretpg
            key: uri