// Code generated by sqlc. DO NOT EDIT.

package posts

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	GetPost(ctx context.Context, id string) (Post, error)
	GetPosts(ctx context.Context) ([]Post, error)
	GetTrendingTodayPostIDs(ctx context.Context) ([]string, error)
	GetTrendingTodayPosts(ctx context.Context) ([]GetTrendingTodayPostsRow, error)
	HasUserLikedPost(ctx context.Context, arg HasUserLikedPostParams) (bool, error)
	LikePost(ctx context.Context, arg LikePostParams) (Post, error)
	RemoveLikeFromPost(ctx context.Context, arg RemoveLikeFromPostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
