// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package testing

import (
	context "context"
	"github.com/DagDigg/unpaper/backend/pkg/api/v1"
	"google.golang.org/grpc/metadata"
	sync "sync"
)

// Ensure, that UnpaperService_ListenForMessagesServerMock does implement v1.UnpaperService_ListenForMessagesServer.
// If this is not the case, regenerate this file with moq.
var _ v1.UnpaperService_ListenForMessagesServer = &UnpaperService_ListenForMessagesServerMock{}

// UnpaperService_ListenForMessagesServerMock is a mock implementation of v1.UnpaperService_ListenForMessagesServer.
//
// 	func TestSomethingThatUsesUnpaperService_ListenForMessagesServer(t *testing.T) {
//
// 		// make and configure a mocked v1.UnpaperService_ListenForMessagesServer
// 		mockedUnpaperService_ListenForMessagesServer := &UnpaperService_ListenForMessagesServerMock{
// 			ContextFunc: func() context.Context {
// 				panic("mock out the Context method")
// 			},
// 			RecvMsgFunc: func(m interface{}) error {
// 				panic("mock out the RecvMsg method")
// 			},
// 			SendFunc: func(chatMessage *v1.ChatMessage) error {
// 				panic("mock out the Send method")
// 			},
// 			SendHeaderFunc: func(mD metadata.MD) error {
// 				panic("mock out the SendHeader method")
// 			},
// 			SendMsgFunc: func(m interface{}) error {
// 				panic("mock out the SendMsg method")
// 			},
// 			SetHeaderFunc: func(mD metadata.MD) error {
// 				panic("mock out the SetHeader method")
// 			},
// 			SetTrailerFunc: func(mD metadata.MD)  {
// 				panic("mock out the SetTrailer method")
// 			},
// 		}
//
// 		// use mockedUnpaperService_ListenForMessagesServer in code that requires v1.UnpaperService_ListenForMessagesServer
// 		// and then make assertions.
//
// 	}
type UnpaperService_ListenForMessagesServerMock struct {
	// ContextFunc mocks the Context method.
	ContextFunc func() context.Context

	// RecvMsgFunc mocks the RecvMsg method.
	RecvMsgFunc func(m interface{}) error

	// SendFunc mocks the Send method.
	SendFunc func(chatMessage *v1.ChatMessage) error

	// SendHeaderFunc mocks the SendHeader method.
	SendHeaderFunc func(mD metadata.MD) error

	// SendMsgFunc mocks the SendMsg method.
	SendMsgFunc func(m interface{}) error

	// SetHeaderFunc mocks the SetHeader method.
	SetHeaderFunc func(mD metadata.MD) error

	// SetTrailerFunc mocks the SetTrailer method.
	SetTrailerFunc func(mD metadata.MD)

	// calls tracks calls to the methods.
	calls struct {
		// Context holds details about calls to the Context method.
		Context []struct {
		}
		// RecvMsg holds details about calls to the RecvMsg method.
		RecvMsg []struct {
			// M is the m argument value.
			M interface{}
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// ChatMessage is the chatMessage argument value.
			ChatMessage *v1.ChatMessage
		}
		// SendHeader holds details about calls to the SendHeader method.
		SendHeader []struct {
			// MD is the mD argument value.
			MD metadata.MD
		}
		// SendMsg holds details about calls to the SendMsg method.
		SendMsg []struct {
			// M is the m argument value.
			M interface{}
		}
		// SetHeader holds details about calls to the SetHeader method.
		SetHeader []struct {
			// MD is the mD argument value.
			MD metadata.MD
		}
		// SetTrailer holds details about calls to the SetTrailer method.
		SetTrailer []struct {
			// MD is the mD argument value.
			MD metadata.MD
		}
	}
	lockContext    sync.RWMutex
	lockRecvMsg    sync.RWMutex
	lockSend       sync.RWMutex
	lockSendHeader sync.RWMutex
	lockSendMsg    sync.RWMutex
	lockSetHeader  sync.RWMutex
	lockSetTrailer sync.RWMutex
}

// Context calls ContextFunc.
func (mock *UnpaperService_ListenForMessagesServerMock) Context() context.Context {
	if mock.ContextFunc == nil {
		panic("UnpaperService_ListenForMessagesServerMock.ContextFunc: method is nil but UnpaperService_ListenForMessagesServer.Context was just called")
	}
	callInfo := struct {
	}{}
	mock.lockContext.Lock()
	mock.calls.Context = append(mock.calls.Context, callInfo)
	mock.lockContext.Unlock()
	return mock.ContextFunc()
}

// ContextCalls gets all the calls that were made to Context.
// Check the length with:
//     len(mockedUnpaperService_ListenForMessagesServer.ContextCalls())
func (mock *UnpaperService_ListenForMessagesServerMock) ContextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockContext.RLock()
	calls = mock.calls.Context
	mock.lockContext.RUnlock()
	return calls
}

// RecvMsg calls RecvMsgFunc.
func (mock *UnpaperService_ListenForMessagesServerMock) RecvMsg(m interface{}) error {
	if mock.RecvMsgFunc == nil {
		panic("UnpaperService_ListenForMessagesServerMock.RecvMsgFunc: method is nil but UnpaperService_ListenForMessagesServer.RecvMsg was just called")
	}
	callInfo := struct {
		M interface{}
	}{
		M: m,
	}
	mock.lockRecvMsg.Lock()
	mock.calls.RecvMsg = append(mock.calls.RecvMsg, callInfo)
	mock.lockRecvMsg.Unlock()
	return mock.RecvMsgFunc(m)
}

// RecvMsgCalls gets all the calls that were made to RecvMsg.
// Check the length with:
//     len(mockedUnpaperService_ListenForMessagesServer.RecvMsgCalls())
func (mock *UnpaperService_ListenForMessagesServerMock) RecvMsgCalls() []struct {
	M interface{}
} {
	var calls []struct {
		M interface{}
	}
	mock.lockRecvMsg.RLock()
	calls = mock.calls.RecvMsg
	mock.lockRecvMsg.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *UnpaperService_ListenForMessagesServerMock) Send(chatMessage *v1.ChatMessage) error {
	if mock.SendFunc == nil {
		panic("UnpaperService_ListenForMessagesServerMock.SendFunc: method is nil but UnpaperService_ListenForMessagesServer.Send was just called")
	}
	callInfo := struct {
		ChatMessage *v1.ChatMessage
	}{
		ChatMessage: chatMessage,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(chatMessage)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//     len(mockedUnpaperService_ListenForMessagesServer.SendCalls())
func (mock *UnpaperService_ListenForMessagesServerMock) SendCalls() []struct {
	ChatMessage *v1.ChatMessage
} {
	var calls []struct {
		ChatMessage *v1.ChatMessage
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}

// SendHeader calls SendHeaderFunc.
func (mock *UnpaperService_ListenForMessagesServerMock) SendHeader(mD metadata.MD) error {
	if mock.SendHeaderFunc == nil {
		panic("UnpaperService_ListenForMessagesServerMock.SendHeaderFunc: method is nil but UnpaperService_ListenForMessagesServer.SendHeader was just called")
	}
	callInfo := struct {
		MD metadata.MD
	}{
		MD: mD,
	}
	mock.lockSendHeader.Lock()
	mock.calls.SendHeader = append(mock.calls.SendHeader, callInfo)
	mock.lockSendHeader.Unlock()
	return mock.SendHeaderFunc(mD)
}

// SendHeaderCalls gets all the calls that were made to SendHeader.
// Check the length with:
//     len(mockedUnpaperService_ListenForMessagesServer.SendHeaderCalls())
func (mock *UnpaperService_ListenForMessagesServerMock) SendHeaderCalls() []struct {
	MD metadata.MD
} {
	var calls []struct {
		MD metadata.MD
	}
	mock.lockSendHeader.RLock()
	calls = mock.calls.SendHeader
	mock.lockSendHeader.RUnlock()
	return calls
}

// SendMsg calls SendMsgFunc.
func (mock *UnpaperService_ListenForMessagesServerMock) SendMsg(m interface{}) error {
	if mock.SendMsgFunc == nil {
		panic("UnpaperService_ListenForMessagesServerMock.SendMsgFunc: method is nil but UnpaperService_ListenForMessagesServer.SendMsg was just called")
	}
	callInfo := struct {
		M interface{}
	}{
		M: m,
	}
	mock.lockSendMsg.Lock()
	mock.calls.SendMsg = append(mock.calls.SendMsg, callInfo)
	mock.lockSendMsg.Unlock()
	return mock.SendMsgFunc(m)
}

// SendMsgCalls gets all the calls that were made to SendMsg.
// Check the length with:
//     len(mockedUnpaperService_ListenForMessagesServer.SendMsgCalls())
func (mock *UnpaperService_ListenForMessagesServerMock) SendMsgCalls() []struct {
	M interface{}
} {
	var calls []struct {
		M interface{}
	}
	mock.lockSendMsg.RLock()
	calls = mock.calls.SendMsg
	mock.lockSendMsg.RUnlock()
	return calls
}

// SetHeader calls SetHeaderFunc.
func (mock *UnpaperService_ListenForMessagesServerMock) SetHeader(mD metadata.MD) error {
	if mock.SetHeaderFunc == nil {
		panic("UnpaperService_ListenForMessagesServerMock.SetHeaderFunc: method is nil but UnpaperService_ListenForMessagesServer.SetHeader was just called")
	}
	callInfo := struct {
		MD metadata.MD
	}{
		MD: mD,
	}
	mock.lockSetHeader.Lock()
	mock.calls.SetHeader = append(mock.calls.SetHeader, callInfo)
	mock.lockSetHeader.Unlock()
	return mock.SetHeaderFunc(mD)
}

// SetHeaderCalls gets all the calls that were made to SetHeader.
// Check the length with:
//     len(mockedUnpaperService_ListenForMessagesServer.SetHeaderCalls())
func (mock *UnpaperService_ListenForMessagesServerMock) SetHeaderCalls() []struct {
	MD metadata.MD
} {
	var calls []struct {
		MD metadata.MD
	}
	mock.lockSetHeader.RLock()
	calls = mock.calls.SetHeader
	mock.lockSetHeader.RUnlock()
	return calls
}

// SetTrailer calls SetTrailerFunc.
func (mock *UnpaperService_ListenForMessagesServerMock) SetTrailer(mD metadata.MD) {
	if mock.SetTrailerFunc == nil {
		panic("UnpaperService_ListenForMessagesServerMock.SetTrailerFunc: method is nil but UnpaperService_ListenForMessagesServer.SetTrailer was just called")
	}
	callInfo := struct {
		MD metadata.MD
	}{
		MD: mD,
	}
	mock.lockSetTrailer.Lock()
	mock.calls.SetTrailer = append(mock.calls.SetTrailer, callInfo)
	mock.lockSetTrailer.Unlock()
	mock.SetTrailerFunc(mD)
}

// SetTrailerCalls gets all the calls that were made to SetTrailer.
// Check the length with:
//     len(mockedUnpaperService_ListenForMessagesServer.SetTrailerCalls())
func (mock *UnpaperService_ListenForMessagesServerMock) SetTrailerCalls() []struct {
	MD metadata.MD
} {
	var calls []struct {
		MD metadata.MD
	}
	mock.lockSetTrailer.RLock()
	calls = mock.calls.SetTrailer
	mock.lockSetTrailer.RUnlock()
	return calls
}
