apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: connected-customers
spec:
  database: unpaper
  name: connected_customers
  schema:
    postgres:
      primaryKey:
        - user_id
      columns:
        - name: user_id
          type: character varying(100)
          constraints:
            notNull: true
        - name: customer_id
          type: character varying(100)
          constraints:
            notNull: true
        - name: connected_customer_id
          type: character varying(100)
          constraints:
            notNull: true
        - name: account_id
          type: character varying(100)
          constraints:
            notNull: true
