apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: mixes
spec:
  database: unpaper
  name: mixes
  schema:
    postgres:
      primaryKey:
        - id
      columns:
        - name: id
          type: character varying(100)
          constraints:
            notNull: true
        - name: user_id
          type: character varying(100)
          constraints:
            notNull: true
        - name: category
          type: character varying(100)
          constraints:
            notNull: true
        - name: post_ids
          type: "character varying(100)[]"
          default: "{}"
          constraints:
            notNull: true
        - name: background
          type: json
          constraints:
            notNull: true
        - name: requested_at
          type: timestamp with time zone
          constraints:
            notNull: true
        - name: title
          type: character varying(100)
          constraints:
            notNull: true
