// Code generated by sqlc. DO NOT EDIT.

package mixes

import (
	"context"
)

type Querier interface {
	CreateUserMix(ctx context.Context, arg CreateUserMixParams) (Mix, error)
	DeleteUserMixes(ctx context.Context, userID string) error
	GetUserMixes(ctx context.Context, userID string) ([]Mix, error)
}

var _ Querier = (*Queries)(nil)
