// Code generated by sqlc. DO NOT EDIT.

package lists

import (
	"context"
)

type Querier interface {
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	GetListByID(ctx context.Context, id string) (List, error)
	GetListsByOwnerID(ctx context.Context, ownerUserID string) ([]List, error)
	UpdateAllowedUsers(ctx context.Context, arg UpdateAllowedUsersParams) (List, error)
	UpdateName(ctx context.Context, arg UpdateNameParams) (List, error)
}

var _ Querier = (*Queries)(nil)
